name: Cargar Asistencia Motorizado

on:
  schedule:
    - cron: '20 3 * * *'
  workflow_dispatch:

jobs:
  procesar:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Clonar repositorio
        uses: actions/checkout@v3

      - name: ðŸ“¦ Instalar Python y dependencias
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ðŸ“¦ Instalar librerÃ­as necesarias
        run: pip install pandas openpyxl

      - name: ðŸ“¦ Instalar rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: ðŸ“ Crear carpeta data/
        run: mkdir data

      - name: ðŸ“¥ Descargar archivos desde OneDrive con rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          echo "$RCLONE_CONF" > rclone.conf
          rclone --config rclone.conf copy "bd_logix:ASISTENCIA/1.xlsx" data/
          rclone --config rclone.conf copy "bd_logix:ASISTENCIA/Reporte_AlmacÃ©n_Asistencia.xlsx" data/
      - name: ðŸ“‚ Verificar archivos descargados
        run: ls -lh data/
      - name: â–¶ï¸ Ejecutar script Python
        run: python 01BD_CARGA_ASISTENCIA_MOTRZD_excel.py

      - name: ðŸ“¤ Subir resultado a OneDrive
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          echo "$RCLONE_CONF" > rclone.conf
          FECHA=$(date +'%Y-%m-%d')
          ARCHIVO="df_merged_motorizado_$FECHA.xlsx"
          rclone --config rclone.conf copy "salida/$ARCHIVO" "bd_logix:ASISTENCIA/RESULTADOS/" --create-empty-src-dirs
